"""
Xcode, simulators and CocoaPods.

Xcode is reliably the largest reclaim on a developer machine after browsers. DeviceSupport
in particular accumulates a directory per iOS point release you have ever connected to,
and nothing ever removes them.
"""

from __future__ import annotations

from mc.registry import Context, Risk, cleanup_module


@cleanup_module(
    name="xcode",
    risk=Risk.STANDARD,
    title="Xcode derived data and archives",
    requires_any=("~/Library/Developer/Xcode", "/Applications/Xcode.app"),
    tags=("dev", "xcode"),
)
def xcode(ctx: Context) -> None:
    """Build products, caches and indexes. All regenerated by the next build."""

    with ctx.step("Clearing Xcode derived data") as step:
        step.path(
            "~/Library/Developer/Xcode/DerivedData/*",
            "~/Library/Developer/Xcode/Products/*",
            "~/Library/Developer/Xcode/iOS Device Logs/*",
            "~/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/*",
        )

    with ctx.step("Clearing Xcode caches") as step:
        step.path(
            "~/Library/Caches/com.apple.dt.Xcode/*",
            "~/Library/Developer/CoreSimulator/Caches/*",
            "~/Library/Developer/Xcode/DocumentationCache/*",
            # Swift module cache and Previews scratch space.
            "~/Library/Developer/Xcode/ModuleCache.noindex/*",
            "~/Library/Developer/Xcode/UserData/Previews/*",
        )

    with ctx.step("Clearing Swift Package Manager cache") as step:
        step.path(
            "~/Library/Caches/org.swift.swiftpm/*",
            "~/Library/org.swift.swiftpm/cache/*",
        )


@cleanup_module(
    name="xcode_archives",
    risk=Risk.AGGRESSIVE,
    title="Xcode archives",
    requires=("~/Library/Developer/Xcode/Archives",),
    tags=("dev", "xcode"),
)
def xcode_archives(ctx: Context) -> None:
    """
    Built .xcarchive bundles.

    Separate from the module above because archives are the artefact you would upload to
    the App Store — they are not automatically regenerated, they are rebuilt by choice.
    Quarantined like everything else at this tier, so a mistake is recoverable.
    """

    with ctx.step("Removing Xcode archives") as step:
        step.path("~/Library/Developer/Xcode/Archives/*")


@cleanup_module(
    name="xcode_device_support",
    risk=Risk.AGGRESSIVE,
    title="Xcode device support",
    requires_any=(
        "~/Library/Developer/Xcode/iOS DeviceSupport",
        "~/Library/Developer/Xcode/watchOS DeviceSupport",
        "~/Library/Developer/Xcode/tvOS DeviceSupport",
    ),
    tags=("dev", "xcode"),
)
def xcode_device_support(ctx: Context) -> None:
    """
    Symbol caches for every OS version you have ever debugged against.

    Typically 2-4 GB per platform. Xcode re-downloads what it needs the next time you
    attach that device, which costs a few minutes once.
    """

    with ctx.step("Removing Xcode device support caches") as step:
        step.path(
            "~/Library/Developer/Xcode/iOS DeviceSupport/*",
            "~/Library/Developer/Xcode/watchOS DeviceSupport/*",
            "~/Library/Developer/Xcode/tvOS DeviceSupport/*",
            "~/Library/Developer/Xcode/macOS DeviceSupport/*",
        )


@cleanup_module(
    name="xcode_simulators",
    risk=Risk.AGGRESSIVE,
    title="Xcode simulators",
    requires_binary=("xcrun",),
    requires=("~/Library/Developer/CoreSimulator",),
    tags=("dev", "xcode"),
)
def xcode_simulators(ctx: Context) -> None:
    """
    Prune unavailable simulator runtimes.

    ``simctl delete unavailable`` — the one from the original script — only removes
    simulators whose runtime is no longer installed, so it cannot take a device you are
    currently using. Simulator data directories are reported but not deleted.
    """

    with ctx.step("Pruning unavailable simulators") as step:
        step.quit_app("Simulator")
        step.command(["/usr/bin/xcrun", "simctl", "shutdown", "all"], timeout=300)
        step.command(["/usr/bin/xcrun", "simctl", "delete", "unavailable"], timeout=900)

    with ctx.step("Clearing simulator caches") as step:
        step.path(
            "~/Library/Developer/CoreSimulator/Caches/dyld/*",
            "~/Library/Developer/CoreSimulator/Devices/*/data/Library/Caches/*",
            "~/Library/Developer/CoreSimulator/Devices/*/data/tmp/*",
        )
        # Installed apps and their data inside each simulator: reported, never deleted.
        # Wiping these silently destroys test fixtures and login state.
        step.measure("~/Library/Developer/CoreSimulator/Devices/*/data/Containers")


@cleanup_module(
    name="cocoapods",
    risk=Risk.STANDARD,
    title="CocoaPods cache",
    requires_binary=("pod",),
    tags=("dev",),
)
def cocoapods(ctx: Context) -> None:
    """CocoaPods download cache and the specs repo checkout."""

    with ctx.step("Cleaning CocoaPods cache") as step:
        step.command([ctx.which("pod") or "pod", "cache", "clean", "--all"], timeout=600)
        step.path("~/Library/Caches/CocoaPods/*")
